### PR TITLE
Cleanup of the wolfSSL user_setting.h

### PR DESCRIPTION
**Pull request by dgarske**
Disable the `OPENSSL_ALL` option by default.

### CODE REVIEW

**Comment by dgarske** [comment]
Related to: https://github.com/wolfSSL/wolfssl/issues/4241

**Comment by dgarske** [comment]
@mahavirj , any feedback on this PR?

**Comment by AdityaHPatwardhan** [comment]
@dgarske Thank you for the PR. sorry for the delayed turnaround. 
 I just had one concern.
Can you please enable the `OPENSSL_EXTRA` option in this case. As we use `wolfSSL_SHA1` API internally with `IDF` (see [link](https://github.com/espressif/esp-idf/blob/eb1a66e7c9468bb71b5440805e395f4c9c0d769f/components/esp-tls/esp-tls-crypto/esp_tls_crypto.c#L47)) and the example fails to compile if both `OPENSSL_EXTRA` and `OPENSSL_ALL` options are disabled.

**Comment by AdityaHPatwardhan** [comment]
Thanks @dgarske for the changes. I have raised the MR in our internal codebase, it should be available publicly in a couple of days

**Review by mahavirj — APPROVED** [review]

**Pull request closed without merging**
